Enable clearing of sink scratchpad
wirepas/gateway pull request #276
Opened 2024-09-06 10:16 UTC by sgunes-wirepas

According to the gateway to backend API, scratchpad should be cleared if the scratchpad bytes are not present in the upload scratchpad request.

In order to make it easier to test OTAP functionality of the gateway, this change enables clearing of the scratchpad when upload scratchpad request with no scratchpad is received on the sink service,

2024-09-06 10:37 UTC, teemupiiroinenwirepas commented
Is there some use case when the scratchpad should be cleared e.g. should backend support it?

2024-09-06 11:54 UTC, sgunes-wirepas commented
> Is there some use case when the scratchpad should be cleared e.g. should backend support it?

Not that I know of, this was only needed to make internal testing more flexible.

Before this change, making an update request with no bytes would result in an error response. Might be good to check if there are any assumptions on the backend side related to this.

2024-09-16 11:43 UTC, GwendalRaoul requested changes
Except the comment on the seq, I'm fine with the change

2024-09-17 06:02 UTC, MauriKuorilehto approved these changes

2024-09-19 08:44 UTC, GwendalRaoul approved these changes

2024-09-19 08:58 UTC, merged